
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - '5678:5678'
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=localhost
      - N8N_PORT=5678
    restart: always
